abbr -a -U -- hb 'ghe branch'
abbr -a -U -- hbc 'ghe checkout -b'
abbr -a -U -- hc 'ghe commit'
abbr -a -U -- hcF 'ghe commit --amend'
abbr -a -U -- hco 'ghe checkout'
abbr -a -U -- hcv 'ghe commit --verbose'
abbr -a -U -- hd 'ghe describe'
abbr -a -U -- hfm 'ghe pull'
abbr -a -U -- hfr 'ghe pull --rebase'
abbr -a -U -- hfc 'ghe clone'
abbr -a -U -- hia 'ghe add'
abbr -a -U -- hir 'ghe restore --staged'
abbr -a -U -- hp 'ghe push'
abbr -a -U -- hpc 'ghe push --set-upstream origin (fish -c git_branch_name)'
abbr -a -U -- hpf 'ghe push --force'
abbr -a -U -- hpt 'ghe push --tags'
abbr -a -U -- hr 'ghe rebase'
abbr -a -U -- hra 'ghe rebase --abort'
abbr -a -U -- hrc 'ghe rebase --continue'
abbr -a -U -- hri 'ghe rebase --interactive'
abbr -a -U -- hrb 'ghe browse'
abbr -a -U -- hs 'ghe stash'
abbr -a -U -- hsp 'ghe stash pop'
abbr -a -U -- ht 'ghe tag'
abbr -a -U -- hwS 'ghe status'
abbr -a -U -- hpd 'ghe pull-request -d'
abbr -a -U -- hpp 'ghe pull-request -p'
abbr -a -U -- hRl 'ghe remote -v'
abbr -a -U -- hRa 'ghe remote -v'
abbr -a -U -- hpp 'ghe pull-request -p'
abbr -a -U -- hpd 'ghe pull-request -d'
