abbr -a -- hb 'ghe branch'
abbr -a -- hbc 'ghe checkout -b'
abbr -a -- hc 'ghe commit'
abbr -a -- hcF 'ghe commit --amend'
abbr -a -- hco 'ghe checkout'
abbr -a -- hcv 'ghe commit --verbose'
abbr -a -- hd 'ghe describe'
abbr -a -- hfm 'ghe pull'
abbr -a -- hfr 'ghe pull --rebase'
abbr -a -- hfc 'ghe clone'
abbr -a -- hia 'ghe add'
abbr -a -- hir 'ghe restore --staged'
abbr -a -- hp 'ghe push'
abbr -a -- hpc 'ghe push --set-upstream origin (fish -c git_branch_name)'
abbr -a -- hpf 'ghe push --force'
abbr -a -- hpt 'ghe push --tags'
abbr -a -- hr 'ghe rebase'
abbr -a -- hra 'ghe rebase --abort'
abbr -a -- hrc 'ghe rebase --continue'
abbr -a -- hri 'ghe rebase --interactive'
abbr -a -- hrb 'ghe browse'
abbr -a -- hs 'ghe stash'
abbr -a -- hsp 'ghe stash pop'
abbr -a -- ht 'ghe tag'
abbr -a -- hwS 'ghe status'
abbr -a -- hpd 'ghe pull-request -d'
abbr -a -- hpp 'ghe pull-request -p'
abbr -a -- hRl 'ghe remote -v'
abbr -a -- hRa 'ghe remote -v'
abbr -a -- hpp 'ghe pull-request -p'
abbr -a -- hpd 'ghe pull-request -d'
