abbr -a -- g git
abbr -a -- gb 'git branch'
abbr -a -- gbc 'git checkout -b'
abbr -a -- gc 'git commit'
abbr -a -- gcF 'git commit --amend'
abbr -a -- gco 'git checkout'
abbr -a -- gcv 'git commit --verbose'
abbr -a -- gd 'git describe'
abbr -a -- gfm 'git pull'
abbr -a -- gfr 'git pull --rebase'
abbr -a -- gfc 'git clone'
abbr -a -- gia 'git add'
abbr -a -- gir 'git restore --staged'
abbr -a -- gp 'git push'
abbr -a -- gpc 'git push --set-upstream origin (git branch --show-current)'
abbr -a -- gpf 'git push --force'
abbr -a -- gpt 'git push --tags'
abbr -a -- gr 'git rebase'
abbr -a -- gra 'git rebase --abort'
abbr -a -- grc 'git rebase --continue'
abbr -a -- gri 'git rebase --interactive'
abbr -a -- grb 'git browse'
abbr -a -- gs 'git stash'
abbr -a -- gsp 'git stash pop'
abbr -a -- gt 'git tag'
abbr -a -- gwS 'git status'
abbr -a -- gpd 'git pull-request -d'
abbr -a -- gpp 'git pull-request -p'
abbr -a -- gRl 'git remote -v'
abbr -a -- gRa 'git remote add'
abbr -a -- gpp 'git pull-request -p'
abbr -a -- gpd 'git pull-request -d'
