abbr -a -U -- g git
abbr -a -U -- gb 'git branch'
abbr -a -U -- gbc 'git checkout -b'
abbr -a -U -- gc 'git commit'
abbr -a -U -- gcF 'git commit --amend'
abbr -a -U -- gco 'git checkout'
abbr -a -U -- gcv 'git commit --verbose'
abbr -a -U -- gd 'git describe'
abbr -a -U -- gfm 'git pull'
abbr -a -U -- gfr 'git pull --rebase'
abbr -a -U -- gfc 'git clone'
abbr -a -U -- gia 'git add'
abbr -a -U -- gir 'git restore --staged'
abbr -a -U -- gp 'git push'
abbr -a -U -- gpc 'git push --set-upstream origin (git branch --show-current)'
abbr -a -U -- gpf 'git push --force'
abbr -a -U -- gpt 'git push --tags'
abbr -a -U -- gr 'git rebase'
abbr -a -U -- gra 'git rebase --abort'
abbr -a -U -- grc 'git rebase --continue'
abbr -a -U -- gri 'git rebase --interactive'
abbr -a -U -- grb 'git browse'
abbr -a -U -- gs 'git stash'
abbr -a -U -- gsp 'git stash pop'
abbr -a -U -- gt 'git tag'
abbr -a -U -- gwS 'git status'
abbr -a -U -- gpd 'git pull-request -d'
abbr -a -U -- gpp 'git pull-request -p'
abbr -a -U -- gRl 'git remote -v'
abbr -a -U -- gRa 'git remote add'
abbr -a -U -- gpp 'git pull-request -p'
abbr -a -U -- gpd 'git pull-request -d'
